ci: add codecov config, publish on release
- includes small readme and changelog revisions
- ci can now be manually triggered

diff --git a/.github/workflows/publish_to_pub.yaml b/.github/workflows/publish_to_pub.yaml
--- a/.github/workflows/publish_to_pub.yaml
+++ b/.github/workflows/publish_to_pub.yaml
@@ -1,8 +1,7 @@
 name: publish_to_pub
 on:
-  push:
-    branches:
-      - master
+  release:
+    types: [published]
 
 jobs:
   publish:
@@ -12,7 +11,17 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Publish to pub
+        id: publish
         uses: k-paxian/dart-package-publisher@master
         with:
           skipTests: true
           credentialJson: ${{ secrets.CREDENTIAL_JSON }}
+
+      - name: Verify published
+        run: |
+          if [ "${{steps.publish.outputs.success}}" = "false" ]; then
+            echo "Publishing failed."
+            exit 1
+          else
+            exit 0
+          fi
